baseURL: https://vc.camp/

publishDir: "public"
languageCode: en-us
title: VC.Camp
canonifyURLs: true
paginate:  5
enableRobotsTXT: true

defaultContentLanguage: "en"
author:  "Harper Reed"

permalinks:
  post: /:year/:month/:day/:title/
  archives: /:year/:month/:day/:title/

params:
  ga_id: "UA-70650-74"
  description: "Tips and tricks for better video chatting"
  cachebuster: "harper rules"
  name: "Harper Reed"
  email: harper@modest.com
  avatar: "https://0.gravatar.com/avatar/b7a96b3d5b5cfed5228396104cd67b38?s=500"
  favicon:  false
  mainSections: 
    - "post"
  social:
    - name: twitter
      icon: "fab fa-twitter"
      url: "http://twitter.com/harper"
    - name: reading
      icon: "fas fa-book-dead"
      url: "https://reading.lol"
    - name: site
      icon: "fas fa-link"
      url: "http://harper.lol"

disableKinds:
  - taxonomy
  - taxonomyTerm
  - home

